import React from 'react';
import { VsmeData } from '../types';

interface Props {
  data: VsmeData;
}

const VSMEReport: React.FC<Props> = ({ data }) => {
  const currentDate = new Date().toLocaleDateString('en-US');

  const SectionHeader = ({ title, code }: { title: string, code: string }) => (
    <div className="mt-8 mb-4 border-b-2 border-demandio-blue pb-1">
      <h3 className="text-demandio-blue font-bold text-lg uppercase tracking-wider">{title} <span className="text-slate-400 text-sm normal-case ml-2">({code})</span></h3>
    </div>
  );

  const TableRow = ({ label, value }: { label: string, value: string }) => (
    <div className="grid grid-cols-12 border-b border-slate-200 py-3 text-sm">
      <div className="col-span-5 font-bold text-slate-700">{label}</div>
      <div className="col-span-7 text-slate-900">{value || '-'}</div>
    </div>
  );

  return (
    <div className="bg-white p-8 md:p-12 shadow-2xl max-w-4xl mx-auto min-h-screen text-slate-900 font-sans print:shadow-none print:p-0">
      
      {/* Header matching the Excel style */}
      <div className="flex justify-between items-end border-b-4 border-demandio-blue pb-4 mb-8">
        <div>
          <h1 className="text-3xl font-extrabold text-demandio-blue">{data.b1_name}</h1>
          <p className="text-slate-500 font-semibold mt-1">VSME Report (Option B (Comprehensive))</p>
        </div>
        <div className="text-right text-sm font-medium text-slate-500">
          Date: {currentDate}
        </div>
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold uppercase tracking-widest text-slate-800 border-b border-slate-300 pb-2">Basic Module (ESRS S1/G1/E1)</h2>
        
        <SectionHeader title="General & Strategy" code="B1-B2" />
        <div className="bg-slate-50 rounded-lg border border-slate-200 px-6 py-2">
            <TableRow label="Selected Option" value="Option B: Basic + Comprehensive" />
            <TableRow label="Legal Form / NACE" value={`${data.b1_legal_form} / ${data.b1_nace}`} />
            <TableRow label="Turnover / Employees" value={`€ ${parseInt(data.b1_turnover).toLocaleString()} / ${data.b1_employees} HC`} />
            <TableRow label="Transition Practices" value={data.b2_practices} />
        </div>

        <SectionHeader title="Environment" code="B3-B7" />
        <div className="bg-slate-50 rounded-lg border border-slate-200 px-6 py-2">
            <TableRow label="Energy (Total/Ren/Fossil)" value={`Total: ${data.b3_energy_total} | Ren: ${data.b3_energy_ren} | Fos: ${(parseInt(data.b3_energy_total) - parseInt(data.b3_energy_ren))} (MWh)`} />
            <TableRow label="GHG Emissions" value={`Scope 1: ${data.b3_scope1} | Scope 2: ${data.b3_scope2} (tCO2e)`} />
            <TableRow label="Pollution & Sensitive Sites" value={data.b4_pollution} />
            <TableRow label="Water & Waste" value={`Water: ${data.b6_water} m3 | Recycled: ${data.b7_waste_recycled} T`} />
        </div>

        <SectionHeader title="Social & Governance" code="B8-B11" />
        <div className="bg-slate-50 rounded-lg border border-slate-200 px-6 py-2">
            <TableRow label="Workforce" value={`Perm: ${data.b8_perm} | Female: ${data.b8_female}`} />
            <TableRow label="Safety & Pay" value={`Accidents: ${data.b9_accidents} | Min Wage: ${data.b10_minwage}`} />
            <TableRow label="Governance (B11)" value={`Convictions: ${data.b11_convictions} | Fines: € ${data.b11_fines}`} />
        </div>
      </div>

      <div className="mb-8">
        <h2 className="text-xl font-bold uppercase tracking-widest text-demandio-blue border-b border-blue-200 pb-2 mt-10">Business Partners Module (P1-P2)</h2>
        
        <SectionHeader title="Supply Chain & Human Rights" code="P1" />
        <div className="bg-blue-50/50 rounded-lg border border-blue-100 px-6 py-2">
            <TableRow label="Code of Conduct" value={data.bp_code} />
            <TableRow label="Grievance Mechanism" value={data.bp_grievance} />
            <TableRow label="Payment Practices" value={data.bp_payment} />
        </div>

        <SectionHeader title="Climate & Financial Alignment" code="P2" />
        <div className="bg-blue-50/50 rounded-lg border border-blue-100 px-6 py-2">
             <TableRow label="Excluded Sector Revenue" value={data.bp_excluded_rev} />
             <TableRow label="Scope 3 Calculation Status" value={data.bp_scope3_status} />
             <TableRow label="Identified Climate Risks" value={data.bp_climate_risks} />
        </div>
      </div>

      <div className="mt-12 pt-8 border-t border-slate-200 text-center text-xs text-slate-400 font-mono">
        Generated by Demandio Platform | {data.b1_name} | VSME Compliant
      </div>
    </div>
  );
};

export default VSMEReport;